version: '3'

services:
    db:
        image: mongo:4.4-bionic
        ports:
            - 27017:27017
        environment:
            MONGO_INITDB_ROOT_USERNAME: application
            MONGO_INITDB_ROOT_PASSWORD: password
